### ISSUE TITLE
Production build for Raspberry Pi 4

### ISSUE THREAD

**Issue by John-Wilcox** [m4heshd/vuelectro#1]
I'm evaluating vuelectro for use with Raspberry Pi 4 and am unable to build for production because of "unsupported architecture arm".   The solution is to pass --arm7l to electron-builder.  I've tried `npm run electron:build -- -- arm7l` as suggested in some threads, but that did not work.  

Is it that your scripts are not allowing the option to be passed?  If so, is there a quick workaround that will allow me to pass this option?

Regards

**Comment by m4heshd** [comment]
You can use `arch` config option in whatever target you choose inside `vuelectro.config.js > electron_builder`.
For an example if the target platform is linux,
```js
"linux": {
  "target": [
    {
      "target": "AppImage",
      "arch": [
        "arm7l"
      ]
    }
  ]
}
```

**Comment by John-Wilcox** [comment]
Thank you Mahesh.
