### ISSUE TITLE
Can't run vuelectro init

### ISSUE THREAD

**Issue by allard-potma** [m4heshd/vuelectro#2]
When I follow the getting started instructions i'm stuck on 'vuelectro init', Windows(powershell) returns a ObjectNotFound exception.
When I run 'npm install vuelectro --save-dev' I get the following warnings:
npm WARN postcss-modules@4.0.0 requires a peer of postcss@^8.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN postcss-modules-extract-imports@3.0.0 requires a peer of postcss@^8.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN postcss-modules-local-by-default@4.0.0 requires a peer of postcss@^8.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN postcss-modules-scope@3.0.0 requires a peer of postcss@^8.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN postcss-modules-values@4.0.0 requires a peer of postcss@^8.1.0 but none is installed. You must install peer dependencies yourself.

**Comment by m4heshd** [comment]
Hi @allard-potma,
Have you created a Vue project first? If you did please link to a copy of your existing `package.json` file **before the installation** of Vuelectro. And that's also before any failed installation too. Because a failed installation can also alter your dependency tree.

**Comment by allard-potma** [comment]
When i just run `vue create` in a empty directory, this is the resulting [package.json.](https://gist.github.com/allard-potma/246b5531dc42f35fab4edbb3a89194fc)

**Comment by m4heshd** [comment]
Can you try to create a Vue project without any extra plugins like `sass` or any other third party loaders? Because this definitely isn't an issue with Vuelectro since those dependencies are not associated with Vuelectro. All the other versions satisfy required versions.

**Comment by allard-potma** [comment]
When I run with the default Vue3 preset, the problem persists. When I run npm install postcss-reporter postcss before installing vuelectro it seems to work. I think it is a strange NPM thing. I will continue using the plugin, thank you!

Edit: updating node and NPM resolved the issue completely.

**Comment by m4heshd** [comment]
> Edit: updating node and NPM resolved the issue completely.

Glad to know. That was my suspicion. NPM has been acting completely bonkers for the past few weeks. Lemme know if there's anything else I can assist you with.

_I've accidentally edited your own comment with my response before. So weird. 😁_
